# path: argocd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/monitoring.yaml
  - applications/spring-boot.yaml
  - argocd/app-of-apps.yaml
  - applications/redis.yaml