# path : apps/monitoring/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - ../../base/prometheus
    - ../../base/grafanal
    - ../../base/loki
    - ../../base/tempo
    - ../../base/thanos
    - ../../base/otel




