apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - grafana-config.yaml
  - grafana-dashboard-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-datasources-config.yaml