apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    releaseName: tempo
    namespace: observability
    valuesFile: values.yaml
    version: 1.3.1
