apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    namespace: observability
    valuesFile: values.yaml
    version: 6.11.2

helmGlobals:
  chartHome: charts